private["_var"];
_var = [_this,0,"",[""]] call BIS_fnc_param;
if(_var == "") exitWith {""};

switch (_var) do
{
	case "life_inv_oilu": {("images\items\oil_unprocessed.paa")};
	case "life_inv_oilp": {("images\items\oil_processed.paa")};
	case "life_inv_heroinu": {("images\items\heroin_unprocessed.paa")};
	case "life_inv_heroinp": {("images\items\heroin_processed.paa")};
	case "life_inv_cannabis": {("images\items\cannabis.paa")};
	case "life_inv_marijuana": {("images\items\marijuana.paa")};
	case "life_inv_apple": {("images\items\apple.paa")};
	case "life_inv_rabbit": {("images\items\meat.paa")};
	case "life_inv_salema": {("images\items\fish.paa")};
	case "life_inv_ornate": {("images\items\fish.paa")};
	case "life_inv_mackerel": {("images\items\fish.paa")};
	case "life_inv_tuna": {("images\items\fish.paa")};
	case "life_inv_mullet": {("images\items\fish.paa")};
	case "life_inv_catshark": {("images\items\fish.paa")};
	case "life_inv_turtle": {("images\items\turtle.paa")};
	case "life_inv_fishingpoles": {("images\items\fishingpoles.paa")};
	case "life_inv_water": {("images\items\water.paa")};
	case "life_inv_coffee": {("images\items\coffee.paa")};
	case "life_inv_turtlesoup": {("images\items\turtle_soup.paa")};
	case "life_inv_donuts": {("images\items\donut.paa")};
	case "life_inv_fuelE": {("images\items\fuel_can.paa")};
	case "life_inv_fuelF": {("images\items\fuel_can.paa")};
	case "life_inv_pickaxe": {("images\items\pickaxe.paa")};
	case "life_inv_copperore": {("images\items\copper_ore.paa")};
	case "life_inv_ironore": {("images\items\iron_ore.paa")};
	case "life_inv_ironr": {("images\items\iron.paa")};
	case "life_inv_copperr": {("images\items\copper.paa")};
	case "life_inv_sand": {("images\items\sand.paa")};
	case "life_inv_salt": {("images\items\salt_unprocessed.paa")};
	case "life_inv_saltr": {("images\items\salt.paa")};
	case "life_inv_glass": {("images\items\glass.paa")};
	case "life_inv_diamond": {("images\items\diamond_unprocessed.paa")};
	case "life_inv_diamondr": {("images\items\diamond.paa")};
	case "life_inv_tbacon": {("images\items\meat.paa")};
	case "life_inv_redgull": {("images\items\redgull.paa")};
	case "life_inv_lockpick": {("images\items\lockpick.paa")};
	case "life_inv_peach": {("images\items\peach.paa")};
	case "life_inv_coke": {("images\items\cocain_unprocessed.paa")};
	case "life_inv_cokep": {("images\items\cocain_processed.paa")};
	case "life_inv_spikeStrip": {("images\items\spikestrip.paa")};
	case "life_inv_rock": {("images\items\rock.paa")};
	case "life_inv_cement": {("images\items\cement.paa")};
	case "life_inv_goldbar": {("images\items\goldbar.paa")};
	case "life_inv_blastingcharge": {("images\items\blastingcharge.paa")};
	case "life_inv_boltcutter": {("images\items\boltcutter.paa")};
	case "life_inv_defusekit": {("images\items\defusekit.paa")};
	case "life_inv_storagesmall": {("images\items\storagesmall.paa")};
	case "life_inv_storagebig": {("images\items\storagebig.paa")};
};