private["_display","_criminal","_tab","_queryResult","_result","_ret","_crimesDb","_crimesArr","_type"];
disableSerialization;
_ret = [_this,0,ObjNull,[ObjNull]] call BIS_fnc_param;
_criminal = [_this,1,[],[]] call BIS_fnc_param;
_result = format["wantedFetchCrimes:%1",_criminal select 0];

waitUntil{!DB_Async_Active};

_tickTime = diag_tickTime;
_queryResult = [_result,2] call DB_fnc_asyncCall;
_ret = owner _ret;
_crimesArr = [];
_type = _queryResult select 0;
{
	switch _x do
	{
		case "1": {_x = "Conduite sans permis de conduire"};
		case "2": {_x = "Vol de véhicule"};
		case "3": {_x = "Vol de véhicule civil étranger"};
		case "4": {_x = "Conduite sans lumières"};
		case "5": {_x = "Vitesse excessive"};
		case "6": {_x = "Conduite dangereuse"};
		case "7": {_x = "Tentative de vol de véhicule de police"};
		case "8": {_x = "Vol de véhicules de police"};
		case "9": {_x = "Atterrissage dans une zone d'exclusion aérienne"};
		case "10": {_x = "Conduite de véhicules illégaux"};
		case "11": {_x = "Délit De Fuite Après Un Accident"};
		case "12": {_x = "Delit De Fuite Devant La Police"};
		case "13": {_x = "Délit De Fuite Devant La Police"};
		case "14": {_x = "Écraser Un Humain"};
		case "15": {_x = "Résistance à la violence de l'Etat"};
		case "16": {_x = "Ne pas suivre le pôle"};
		case "17": {_x = "Insultes"};
		case "18": {_x = "Harcèlement d'un agent de police"};
		case "19": {_x = "Entrer dans le pôle de la zone de barrage"};
		case "20": {_x = "Tuer un policier"};
		case "21": {_x = "Feu sur la police"};
		case "22": {_x = "Destruction de biens de la police"};
		case "23": {_x = "infractions relatives aux drogues"};
		case "24": {_x = "Possession d'armes à feu sans permis"};
		case "25": {_x = "Arme dans la ville"};
		case "26": {_x = "Possession d'une arme interdite"};
		case "27": {_x = "sage de l'arme à l'intérieur des villes"};
		case "28": {_x = "Prise d'otages"};
		case "29": {_x = "Attaque sur des personnes/véhicules"};
		case "30": {_x = "Hold-up"};
		case "31": {_x = "Meurtre"};
		case "32": {_x = "Révolte"};
		case "33": {_x = "Attaque par le rebelle"};
		case "34": {_x = "Attaque / siège des capitales"};
		case "35": {_x = "atterrissage dans une zone d'exclusion aérienne"};
		case "36": {_x = "Voler en-dessous de 150m à kavala"};
		case "37": {_x = "Sortie de la prison"};
		case "38": {_x = "Voler sans permis de vol"};
		case "39": {_x = "Klaxons gênants durablement"};
		case "40": {_x = "Commerce avec les biens exotiques"};
		case "187V": {_x = "Homicide Routier"};
		case "187": {_x = "Homicide Involontaire"};
		case "207": {_x = "Enlèvement"};
		case "207A": {_x = "Tentative D'enlèvement"};
		case "211": {_x = "Attaque Station De Essence"};
		case "211A": {_x = "Pillage de Distributeur"};
		case "213": {_x = "Utilisation D'explosifs"};
		case "215": {_x = "Tentative De Vol D'Automobile"};
		case "261": {_x = "Viol"};
		case "261A": {_x = "Tentative De Viol"};
		case "459": {_x = "Cambriolage"};
		case "459A": {_x = "Pillage de la reserve fédérale"};
		case "480": {_x = "Délit De Fuite"};
		case "481": {_x = "Possession de substance illicite"};
		case "482": {_x = "Intention De Distribuer"};
		case "483": {_x = "Trafic De Drogue"};
		case "485": {_x = "Tentative de crochetage de menottes"};
		case "486": {_x = "Crochetage de menotte"};
		case "487": {_x = "Grand Vol"};
		case "488": {_x = "Petit Vol"};
		case "800": {_x = "Torture sur humain"};
		case "901": {_x = "Evasion de Prison"};
		case "902": {_x = "Vitesse Excessive"};
		case "9021": {_x = "Vitesse Excessive"};
		case "9022": {_x = "Vitesse Excessive"};
		case "902": {_x = "Sortir un prisonnier"};
		case "919": {_x = "Trafic d'organes"};
	};
	_crimesArr pushBack _x;
} forEach _type;
_queryResult set[0,_crimesArr];

diag_log "------------- Requête Query du client -------------";
diag_log format["QUERY: %1",_result];
diag_log format["Temps à compléter: %1 seconde(s)",(diag_tickTime - _tickTime)];
diag_log format["Resultat: %1",_queryResult];
diag_log "---------------------------------------------------";

[[_queryResult],"life_fnc_wantedInfo",_ret,false] spawn life_fnc_MP;